# Generated by Django 3.1.7 on 2021-03-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(db_column='Category ID', max_length=15, primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='Category Name', max_length=50)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
    ]
