# Generated by Django 3.1.7 on 2021-03-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product_info',
        ),
    ]
