# Generated by Django 3.1.7 on 2021-03-31 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210331_2234'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='ProductInfo',
        ),
    ]
