# Generated by Django 3.1.7 on 2021-04-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210331_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(db_column='Category Name', max_length=100, primary_key=True, serialize=False),
        ),
    ]
