# Generated by Django 3.1.7 on 2021-03-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(db_column='User ID', max_length=15, primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='User Name', max_length=50)),
                ('user_age', models.IntegerField(db_column='Age', max_length=3)),
                ('user_email', models.EmailField(db_column='Email', max_length=50)),
                ('user_phone', models.CharField(db_column='Phone', max_length=20)),
                ('user_address', models.CharField(db_column='Address', max_length=50)),
            ],
            options={
                'db_table': 'User-info',
            },
        ),
    ]
