# Generated by Django 3.1.7 on 2021-03-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210329_1041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
