# Generated by Django 3.1.7 on 2021-04-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
