# Generated by Django 3.1.7 on 2021-04-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210402_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(db_column='Phone', max_length=20),
        ),
    ]
