# Generated by Django 3.1.7 on 2021-04-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210402_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
