# Generated by Django 3.1.7 on 2021-04-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
