# Generated by Django 3.1.7 on 2021-04-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
